#!/bin/bash
#
# Install script for Easy-LDAP
#

# If no "/bin" directory, create a new one
if [ ! -d "$HOME/bin" ]; then
    echo "Creating ~/bin"
    mkdir $HOME/bin
    sleep 1
    echo
fi

# Check what current shell
if [[ "$SHELL" =~ "bash" ]]; then
    FILE=~/.bash_profile
    SHELL_NAME="bash"
elif [[ "$SHELL" =~ "zsh" ]]; then
    FILE=~/.zshrc
    SHELL_NAME="zsh"
elif [[ "$SHELL" =~ "fish" ]]; then
    FILE=~/.config/fish/config.fish
    SHELL_NAME="fish"
fi

# If no "~/shell_config" file, create a new one and then add to PATH
if test -f "$FILE"; then
    if ! grep -qe '$HOME/bin\|~/bin' "$FILE"; then
        echo 'Adding ~/bin to $PATH '$FILE
        if [ "$SHELL_NAME" == "bash" ]; then
            cat assets/bash.md >> ~/.bash_profile
            source ~/.bash_profile
        elif [ "$SHELL_NAME" == "zsh" ]; then
            cat assets/zsh.md >> ~/.zshrc
            source ~/.zshrc
        elif [ "$SHELL_NAME" == "fish" ]; then
            cat assets/fish.md >> ~/.config/fish/config.fish
            source ~/.config/fish/config.fish
        fi
        sleep 1
        echo
    fi
else
    echo "Creating $FILE"
    echo 'Adding ~/bin to $PATH '$FILE
    if [ "$SHELL_NAME" == "bash" ]; then
        touch ~/.bash_profile
        cat assets/bash.md >> ~/.bash_profile
        source ~/.bash_profile
    elif [ "$SHELL_NAME" == "zsh" ]; then
        touch ~/.zshrc
        cat assets/zsh.md >> ~/.zshrc
        source ~/.zshrc
    elif [ "$SHELL_NAME" == "fish" ]; then
        touch ~/.config/fish/config.fish
        cat assets/fish.md >> ~/.config/fish/config.fish
        source ~/.config/fish/config.fish
    fi
    sleep 1
    echo
fi

# If no "ezldap" in "/bin" directory, copy or symlink
APP_FILE=~/bin/ezldap
if ! test -f "$APP_FILE"; then
    echo "Do you want to copy file or create symlink?" 
    read -p "'1 copy' || '2 symlink' [1/2]: " answer
    if [ $answer == "1" ]; then
        echo "Copying ezldap to ~/bin/"
        cp ezldap ~/bin/;sudo chmod +x ~/bin/ezldap
    else
        echo "Creating symlink for ezldap to ~/bin/"
        ln -s "$PWD/ezldap" ~/bin;sudo chmod +x ~/bin/ezldap
    fi
    sleep 1
    echo
fi

# Get current user name
if ! [ $(id -u) = 0 ]; then
    current_user=$USER
else
    current_user=$SUDO_USER
fi

# If no "/etc/ezldap" directory, then create a new one
if [ ! -d "/etc/ezldap" ]; then
    sudo mkdir /etc/ezldap
fi

# If no "/etc/ezldap/ezldap.conf", create a new one
CONFIG_FILE=/etc/ezldap/ezldap.conf
if ! test -f "$CONFIG_FILE"; then
    echo "Starting to create your config file"
    echo "Config file will be located in /etc/ezldap/"
    sleep 2
    sudo cp assets/ezldap.conf /etc/ezldap/
    sudo "${EDITOR:-nano}" /etc/ezldap/ezldap.conf
    sudo chmod go-r /etc/ezldap/ezldap.conf
    sudo chown $current_user /etc/ezldap/ezldap.conf
fi

# If no "/etc/ezldap/install", copy this script to destination directory
INSTALL_FILE=/etc/ezldap/install
if ! test -f "$INSTALL_FILE"; then
    echo "Copying install to /etc/ezldap"
    sleep 1
    sudo cp install /etc/ezldap/
    sudo chmod 700 /etc/ezldap/install
    sudo chown $current_user /etc/ezldap/install
fi

# If no "/etc/ezldap/uninstall", copy uninstall script to destination directory
UNINSTALL_FILE=/etc/ezldap/uninstall
if ! test -f "$UNINSTALL_FILE"; then
    echo "Copying uninstall to /etc/ezldap"
    sleep 1
    sudo cp uninstall /etc/ezldap/
    sudo chmod 700 /etc/ezldap/uninstall
    sudo chown $current_user /etc/ezldap/uninstall
    exit 1
fi

exit 1
